#define VERSION "2.28.2"
#define GETTEXT_PACKAGE "gnome-games"

#define DATADIR "XXX_DATADIR_XXX"
#define PKGDATADIR "/usr/share/games/"
#define SCORESDIR "XXX_SCORESDIR_XXX"

#define GAMES_CARD_THEME_DEFAULT_FORMAT_STRING "XXX_GAMES_CARD_THEME_DEFAULT_FORMAT_STRING_XXX"
#define GAMES_CARD_THEME_DEFAULT "XXX_GAMES_CARD_THEME_DEFAULT_XXX"
